### ISSUE TITLE
Make *git-messenger* buffer reuses magit-commit-mode if available

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-git-messenger#25]
I think magit-commit-mode is really suitable for `*git-messenger*` buffer to show git output from `d`, `s` and `S` commands. It has highlighting and able to press `q` to quit.

**Comment by cryptomaniac512** [comment]
Hi!
This hook is not working now. I see that magit-commit-mode does not exist now. There is another way to use proposed usability in the first?

Sorry for my bad English.
