### ISSUE TITLE
can you suppport latest subverion?

### ISSUE THREAD

**Issue by redguardtoo** [syohex/emacs-git-messenger#27]
some of my enterprise projects are using svn. latest version of svn is fine which has only one ".svn" directory at the root folder. 

the other issue is sometimes I create a git repo *under* svn root directory. so I need a flag to make svn take priority.

**Comment by syohex** [comment]
I have implemented Subversion support at #28.
Please check latest version with following configuration.

```lisp
(setq git-messenger:handled-backends '(svn git))
```
