### ISSUE TITLE
feature request: check the info of previous commit

### ISSUE THREAD

**Issue by redguardtoo** [syohex/emacs-git-messenger#34]
sometimes the latest commit message is not useful. For example, somebody re-indent the the line, but I'm only interested in the guy who actually implementing the logic.

so, I'd like some hotkey in git-messenger-map which I can keep pressing to get the previous commit.

http://stackoverflow.com/questions/2096491/git-how-to-analyze-code-that-has-a-multi-file-history

**Comment by syohex** [comment]
I have committed initial implementation of this at #40.

**Comment by redguardtoo** [comment]
Can you release a stable version?

**Comment by syohex** [comment]
Done

**Comment by redguardtoo** [comment]
cool, thanks
