### ISSUE TITLE
[Feature request] Add minor mode hook when open pop-up `git show` 

### ISSUE THREAD

**Issue by zw963** [syohex/emacs-git-messenger#35]
Current, when into git-show buffer, it use `fundamental-mode`.

I want binding some exiting this buffer hotkey for this buffer, 
but seem like no idea for this.

thanks.

**Comment by syohex** [comment]
I have enabled view-mode at #36. So the buffer is killed by `q`. Please check latest version.

**Comment by zw963** [comment]
It worked, thanks.
