### ISSUE TITLE
git-messenger:popup-buffer-hook does not work with magit-commit-mode

### ISSUE THREAD

**Issue by cryptomaniac512** [syohex/emacs-git-messenger#41]
Hi!

`magit-commit-mode` does not exists now, so [this](https://github.com/syohex/emacs-git-messenger/issues/25) example can not work.

Can you add `magit` support into your plugin?
You can get some info at [this StackOverflow question](http://emacs.stackexchange.com/questions/29722/) and [answer from `magit` maintainer](http://emacs.stackexchange.com/a/29723/13871).

Sorry for my bad English.

**Comment by syohex** [comment]
I have implement magit support at #42. Could you set following configuration and try ?

```
(custom-set-variables
 '(git-messenger:use-magit-popup t))
```

**Comment by cryptomaniac512** [comment]
Thank you!
But `[s]`, `[S]` and `[d]` now operate identically. Whether they are necessary with `magit` integration?

**Comment by syohex** [comment]
No. I improve minibuffer at #43. Please check it.
